apiVersion: apps/v1
kind: Deployment
metadata:
  name: rain-app
  namespace: default
  labels:
    app: rain-app  
spec:
  selector:
    matchLabels:
      app: rain-app
  replicas: 1
  template:
    metadata:
      labels:
        app: rain-app
    spec:
      containers:
      - name: rain-app
        image: assignment
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.json
          subPath: config.json   
      volumes:
      - name: config-volume
        configMap:
          name: rainconfig