apiVersion: v1
kind: Pod
metadata:
  name: rain-app
  namespace: default
spec:
  containers:
  - name: rain-app
    image: assignment
    imagePullPolicy: Never
    ports:
    - containerPort: 80
    volumeMounts:
    - name: config-volume
      mountPath: /app/config.json
      subPath: config.json   
  volumes:
  - name: config-volume
    configMap:
      name: rainconfig
